---
- name: Set Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_path: /Users/josh/Projects/macbook_config
  tasks:


  - name: Iterm | Install iTerm2 Dracula theme
    tags: iterm
    git:
      repo: "https://github.com/dracula/iterm.git"
      dest: "~/.dracula-themes/iterm2/"

  # - name: Adjust permissions before installing git with brew
  #   command: "sudo chown -R $(whoami) /opt/homebrew /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew/locks && chmod u+w /opt/homebrew /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew/locks"
  #   become: true

  - name: Visual Studio Code | Enable key repeating for VS Code Vim extension
    tags: vscode, vim
    command: "defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false"
    args:
      creates: "~/Library/Preferences/com.microsoft.VSCode.plist"

  - name: zsh | Push ~/.p10k.zsh
    tags: zsh
    copy:
      src: "{{ project_path }}/files/Home/.p10k.zsh"
      dest: "~/.p10k.zsh"
      owner: "{{ lookup('env', 'USER') }}"
      mode: '0644'

  - name: Vim | Push ~/.vimrc
    tags: vim
    copy:
      src: "{{ project_path }}/files/Home/.vimrc"
      dest: "~/.vimrc"
      owner: "{{ lookup('env', 'USER') }}"
      mode: '0644'




  # - name: ohmyzsh | Ensure ~/.oh_my_zsh/custom/plugin directory exists
  #   tags: ohmyzsh, zsh
  #   file:
  #     path: "~/.oh_my_zsh/custom/plugin"
  #     state: directory
  #     mode: '0755'

  # - name: ohmyzsh | clone ohmyzsh project
  #   tags: ohmyzsh, zsh
  #   git:
  #     repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
  #     dest: '~/.oh_my_zsh/'

