- name: "MacOS | Save preference files"
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/Library/Preferences/{{ item }}"
    dest: "{{ project_path }}/files/Home/Library/Preferences/{{ item }}"
    remote_src: yes
    mode: "0644"
  loop:
    - ".GlobalPreferences.plist"
    - ".GlobalPreferences_m.plist"
    - "com.apple.symbolichotkeys.plist"
    - "com.apple.HIToolbox.plist"
    - "com.apple.dock.plist"
    - "com.apple.Accessibility.plist"
    - "com.apple.universalaccess.plist"
  when: "'DefaultKeyBinding.dict' not in item"
  ignore_errors: yes
