  - name: MacOS | Save GlobalPreferences plist (keyboard shortcuts?)
    copy:
      src: "{{ lookup('env', 'HOME') }}/Library/Preferences/.GlobalPreferences.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/.GlobalPreferences.plist"
 
  - name: MacOS | Save GlobalPreferences_m plist (?)
    copy:
      src: "{{ lookup('env', 'HOME') }}/Library/Preferences/.GlobalPreferences_m.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/.GlobalPreferences_m.plist"
    
  - name: MacOS | Save native keybindings
    copy:
      src: "{{ lookup('env', 'HOME') }}/Library/Preferences/com.apple.symbolichotkeys.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/com.apple.symbolichotkeys.plist"

  - name: MacOS | Save general keyboard preferences
    fetch:
      src: "~/Library/Preferences/com.apple.HIToolbox.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/com.apple.HIToolbox.plist"
      flat: yes
          
  - name: MacOS | Check if DefaultKeyBinding.dict exists
    stat:
      path: "~/Library/KeyBindings/DefaultKeyBinding.dict"
    register: keybinding_file

  - name: MacOS | Save keybindings
    fetch:
      src: "~/Library/KeyBindings/DefaultKeyBinding.dict"
      dest: "{{ project_path }}/files/Home/Library/KeyBindings/DefaultKeyBinding.dict"
      flat: yes
    when: keybinding_file.stat.exists

  - name: MacOS | Save dock configuration
    fetch:
      src: "~/Library/Preferences/com.apple.dock.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/com.apple.dock.plist"
      flat: yes