  - name: MacOS | Save native keybindings
    copy:
      src: "{{ lookup('env', 'HOME') }}/Library/Preferences/com.apple.symbolichotkeys.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/com.apple.symbolichotkeys.plist"

  - name: MacOS | Save general keyboard preferences
    fetch:
      src: "~/Library/Preferences/com.apple.HIToolbox.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/com.apple.HIToolbox.plist"
      flat: yes
          
  - name: MacOS | Check if DefaultKeyBinding.dict exists
    stat:
      path: "~/Library/KeyBindings/DefaultKeyBinding.dict"
    register: keybinding_file

  - name: MacOS | Save keybindings
    fetch:
      src: "~/Library/KeyBindings/DefaultKeyBinding.dict"
      dest: "{{ project_path }}/files/Home/Library/KeyBindings/DefaultKeyBinding.dict"
      flat: yes
    when: keybinding_file.stat.exists