
  - name: Backup Terminal user configuration
    ansible.builtin.copy:
      src: "~/Library/Preferences/com.apple.Terminal.plist"
      dest: "{{ project_path }}/files/Home/Library/Preferences/com.apple.Terminal.plist"
      remote_src: yes
      mode: '0644'