---
- name: Git | Check for local changes
  command:
    cmd: git status --porcelain
    chdir: "{{ project_path }}"
  register: git_status
  changed_when: false

- name: Git | Pull configuration from remote repository
  git:
    repo: "https://github.com/lowranceworks/macbook_config.git"
    dest: "{{ project_path }}"
    update: yes
  when: git_status.stdout == ""

- name: Git | Check if 'latest-config' branch exists
  command:
    cmd: git rev-parse --verify latest-config
    chdir: "{{ project_path }}"
  register: branch_check
  ignore_errors: true

- name: Git | Checkout 'latest-config' branch
  command:
    cmd: git checkout latest-config
    chdir: "{{ project_path }}"
  when: branch_check.rc == 0
  register: git_checkout
  changed_when: "'Switched to branch' in git_checkout.stdout"

- name: Git | Create and checkout 'latest-config' branch
  command:
    cmd: git checkout -b latest-config
    chdir: "{{ project_path }}"
  when: branch_check.rc != 0
  register: git_checkout_new
  changed_when: "'Switched to a new branch' in git_checkout_new.stdout"

- name: Git | Ensure the 'latest-config' branch is up to date
  git:
    repo: "https://github.com/lowranceworks/macbook_config.git"
    dest: "{{ project_path }}"
    version: "latest-config"
    force: yes
  when: "'latest-config' in git_checkout_latest_config.stdout"

- block:
    - import_tasks: system/terminal.yaml
      tags: system, terminal

    - import_tasks: system/macos.yaml
      tags: system, macos

    - import_tasks: system/ssh.yaml
      tags: system, ssh

    - import_tasks: software/brew-applications.yaml
      tags: software, applications, brew

    - import_tasks: software/inkdrop.yaml
      tags: software, inkdrop

    - import_tasks: software/iterm.yaml
      tags: software, iterm

    # - import_tasks: software/lunarvim.yaml
    # tags: software, lunarvim

    - import_tasks: software/neovim.yaml
      tags: software, neovim

    - import_tasks: software/vim.yaml
      tags: software, vim

    #  - import_tasks: software/vscode.yaml
    #    tags: software, vscode

    - import_tasks: software/zsh.yaml
      tags: software, zsh, oh-my-zsh

    - import_tasks: software/alfred.yaml
      tags: software, alfred

    - import_tasks: software/cleanshot.yaml
      tags: software, cleanshot

    - import_tasks: software/contexts.yaml
      tags: software, contexts

    - import_tasks: software/fig.yaml
      tags: software, fig

    - import_tasks: software/rectangle-pro.yaml
      tags: software, rectangle-pro

- name: Git | Add all changes
  command:
    cmd: git add --all
    chdir: "{{ project_path }}"

- name: Git | Execute status command
  command:
    cmd: git status
    chdir: "{{ project_path }}"
  register: git_status_result

- name: Git | Commit changes
  command:
    cmd: git commit -m "update configuration files"
    chdir: "{{ project_path }}"
  when: "'Your branch is up to date with' not in git_status_result.stdout"

- name: Git | Push changes
  command:
    cmd: git push --set-upstream origin latest-config
    chdir: "{{ project_path }}"
  when: "'Your branch is up to date with' not in git_status_result.stdout"

- name: Git | Checkout the previous branch
  command:
    cmd: git checkout -
    chdir: "{{ project_path }}"
