---
- name: Git | Check for local changes
  command:
    cmd: git status --porcelain
    chdir: "{{ project_path }}"
  register: git_status
  changed_when: false

- name: Git | Pull configuration from remote repository
  git:
    repo: "https://github.com/lowranceworks/macbook_config.git"
    dest: "{{ project_path }}"
    update: yes
  when: git_status.stdout == ""

- block:
    - import_tasks: system/terminal.yaml
      tags: system, terminal

    - import_tasks: system/macos.yaml
      tags: system, macos

    - import_tasks: system/ssh.yaml
      tags: system, ssh

    - import_tasks: software/brew-applications.yaml
      tags: software, applications, brew

    - import_tasks: software/inkdrop.yaml
      tags: software, inkdrop

    - import_tasks: software/iterm.yaml
      tags: software, iterm

    # - import_tasks: software/lunarvim.yaml
    # tags: software, lunarvim

    - import_tasks: software/neovim.yaml
      tags: software, neovim

    # - import_tasks: software/vim.yaml
    #  tags: software, vim

    #  - import_tasks: software/vscode.yaml
    #    tags: software, vscode

    - import_tasks: software/zsh.yaml
      tags: software, zsh, oh-my-zsh

    - import_tasks: software/oh-my-zsh.yaml
      tags: software, zsh, oh-my-zsh

    - import_tasks: software/alfred.yaml
      tags: software, alfred

    - import_tasks: software/cleanshot.yaml
      tags: software, cleanshot

    - import_tasks: software/contexts.yaml
      tags: software, contexts

    - import_tasks: software/fig.yaml
      tags: software, fig

    - import_tasks: software/rectangle-pro.yaml
      tags: software, rectangle-pro

    - import_tasks: software/tmux.yaml
      tags: software, tmux

    - import_tasks: software/wezterm.yaml
      tags: wezterm

    - import_tasks: software/yabai.yaml
      tags: yabai

    - import_tasks: software/skhd.yaml
      tags: skhd

    - import_tasks: software/spacelauncher.yaml
      tags: spacelauncher

    - import_tasks: software/starship.yaml
      tags: starship

    - import_tasks: software/fish.yaml
      tags: fish
