- block:
  - import_tasks: pull-changes-from-remote-repository.yaml

  - import_tasks: system/terminal.yaml
  - import_tasks: system/macos.yaml
  - import_tasks: system/ssh.yaml

  - import_tasks: software/brew-applications.yaml
  - import_tasks: software/inkdrop.yaml
  - import_tasks: software/iterm.yaml
  - import_tasks: software/lunarvim.yaml
  - import_tasks: software/neovim.yaml
  - import_tasks: software/oh-my-zsh.yaml
  - import_tasks: software/vim.yaml
  - import_tasks: software/vscode.yaml
  - import_tasks: software/zsh.yaml 
  - import_tasks: software/alfred.yaml 

  - import_tasks: push-changes-to-remote-repository.yaml