---
- name: Save Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_path: /Users/josh/Projects/macbook_config
    commit_message: "fix: update configuration files"
    pr_title: "update configuration files"
    pr_body: "These changes were applied by the save-configuration.yaml playbook."
    branch_name: "update-configuration"

  tasks:



  # - name: Add changes from the files directory
  #   command:
  #     cmd: git add files/*
  #     chdir: '{{ project_path }}'
      
  # - name: Commit the changes
  #   command:
  #     cmd: "git commit -m 'fix: update configuration files'"
  #     chdir: '{{ project_path }}'

  # - name: Push changes to the main branch
  #   command:
  #     cmd: git push origin main
  #     chdir: '{{ project_path }}'