
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

# sets user-defined palette (theme)
palette = "catppuccin_mocha"

[directory.substitutions]
# '~/tests/starship-custom' = 'work-project'

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$context(\[$namespace\])]($style) '

[kubernetes.context_aliases]
# 'arn:ws:eks:us-west-2:577926974532:cluster/gal-kub-demo-cluster' = 'gal'

[docker_context]
disabled = true

[gcloud]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold #ffb86c"
symbol = "  "

[aws]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold #ffb86c"
symbol = "  "

[azure]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold #ffb86c"
symbol = "  "

[character]
error_symbol = "[󰩈](bold #f38ba8)"
success_symbol = "[](bold #a6e3a1)"
vicmd_symbol = "[](bold #94e2d5)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]

[git_status]

[hostname]

[username]
format = "[$user]($style) on "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
