- name: Fonts | Tap homebrew/cask-fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

# See font options here: https://gist.github.com/davidteren/898f2dcccd42d9f8680ec69a3a5d350e
- name: Fonts | Install fonts
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    install_options: cask
  loop:
    - font-meslo-lg-nerd-font
    - font-hack-nerd-font
    - font-monaspace
    - font-commit-mono
