- name: Fonts | Tap homebrew/cask-fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

# See font options here: https://gist.github.com/davidteren/898f2dcccd42d9f8680ec69a3a5d350e
- name: Fonts | Install font-hack-nerd-font
  community.general.homebrew:
    name: font-hack-nerd-font
    state: present
    install_options: cask
