- name: "MacOS | Ensure Preferences directory exists"
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/Library/Preferences"
    state: directory
    mode: "0755"

- name: "MacOS | Set preference files"
  ansible.builtin.copy:
    src: "{{ project_path }}/files/Home/Library/Preferences/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/Library/Preferences/{{ item }}"
    mode: "0644"
    remote_src: no
  loop:
    - "com.apple.symbolichotkeys.plist"
    - ".GlobalPreferences.plist"
    - ".GlobalPreferences_m.plist"
    - "com.apple.dock.plist"
    - ".com.apple.Accessibility.plist"
    - ".com.apple.universalaccess.plist"
    - "com.apple.HIToolbox.plist"
