
  - name: SSH | Ensure ~/.ssh directory exists
    file:
      path: "{{ lookup('env', 'HOME') }}/.ssh"
      state: directory
      mode: '0755'

  - name: SSH | Push ~/.ssh/config
    copy:
      src: "{{ project_path }}/files/Home/.ssh/config"
      dest: "~/.ssh/config"
      owner: "{{ lookup('env', 'USER') }}"
      mode: '0600'  # This ensures the config file is readable only by the owner which is usually required for SSH config files
