- name: "Terminal | Ensure Preferences directory exists"
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Preferences"
    state: directory
    mode: '0755'

- name: "Terminal | Restore Terminal user configuration"
  ansible.builtin.copy:
    src: "{{ project_path }}/files/Home/Library/Preferences/com.apple.Terminal.plist"
    dest: "~/Library/Preferences/com.apple.Terminal.plist"
    remote_src: yes
    mode: '0644'
