  - name: Check if Alfred.alfredpreferences directory exists
    tags: alfred
    ansible.builtin.stat:
      path: "~/.alfred-preferences/Alfred.alfredpreferences/"
    register: alfred_prefs

  - name: Alfred | Archive preferences
    tags: alfred
    archive:
      path: "~/.alfred-preferences/Alfred.alfredpreferences/"
      dest: "{{ project_path }}/files/Home/.alfred-preferences/Alfred.alfredpreferences.zip"
      format: zip