  - name: LunarVimVim | Fetch all files from ~/.config/lvim/ recursively
    synchronize:
      src: "~/.config/nvim/"
      dest: "{{ project_path }}/files/Home/.config/nvim/"
      recursive: yes
      mode: pull
