- name: Contexts | Save plist file
  copy:
    src: "~/Library/Preferences/com.contextsformac.Contexts.plist"
    dest: "{{ project_path }}/files/Home/Library/Preferences/com.contextsformac.Contexts.plist"
    remote_src: no


