- name: fish | backup fish shell config
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.config/fish/"
    dest: "{{ project_path }}/files/Home/.config/fish/"
    remote_src: true
    directory_mode: true
