- name: "LunarVim | Check if ~/.config/lvim/ directory exists"
  stat:
    path: "~/.config/lvim/"
  register: lvim_config_stat

- name: "LunarVim | Save all files from ~/.config/lvim/ recursively"
  synchronize:
    src: "~/.config/lvim/"
    dest: "{{ project_path }}/files/Home/.config/lvim/"
    recursive: yes
    mode: pull
  when: lvim_config_stat.stat.exists and lvim_config_stat.stat.isdir

- name: LunarVim | Save keymappings
  synchronize:
    src: "~/.vim/keymappings.vim"
    dest: "{{ project_path }}/files/Home/.vim/keymappings.vim/"
    recursive: yes
    mode: push
