- name: "NeoVim | Check if ~/.config/nvim/ directory exists"
  stat:
    path: "~/.config/nvim/"
  register: neovim_config_stat

- name: "NeoVim | Save all files from ~/.config/nvim/ recursively"
  synchronize:
    src: "~/.config/nvim/"
    dest: "{{ project_path }}/files/Home/.config/nvim/"
    recursive: yes
    mode: pull
  when: neovim_config_stat.stat.exists and neovim_config_stat.stat.isdir

# - name: NeoVim | Save keymappings
#   synchronize:
#     src: "~/.vim/keymappings.vim"
#     dest: "{{ project_path }}/files/Home/.vim/keymappings.vim/"
#     recursive: yes
#     mode: push