- name: "Rectangle Pro | Check if com.knollsoft.Rectangle.plist exists"
  stat:
    path: "~/Library/Preferences/com.knollsoft.Rectangle.plist"
  register: rectangle_plist_stat

- name: "Rectangle Pro | Save com.knollsoft.Rectangle.plist file"
  copy:
    src: "~/Library/Preferences/com.knollsoft.Rectangle.plist"
    dest: "{{ project_path }}/files/Home/Library/Preferences/com.knollsoft.Rectangle.plist"
    remote_src: no
  when: rectangle_plist_stat.stat.exists

- name: "Rectangle Pro | Check if RectangleProConfig.json exists"
  stat:
    path: "~/Downloads/RectangleProConfig.json"
  register: rectangleproconfig

- name: "Rectangle Pro | Save RectangleProConfig.json file"
  copy:
    src: "~/Downloads/RectangleProConfig.json"
    dest: "{{ project_path }}/files/Home/Library/Application Support/Rectangle Pro/RectangleProConfig.json"
    remote_src: yes
  when: rectangleproconfig.stat.exists
