- name: Rectangle Pro | Save com.knollsoft.Rectangle.plist file
  copy:
    src: "~/Library/Preferences/com.knollsoft.Rectangle.plist"
    dest: "{{ project_path }}/files/Home/Library/Preferences/com.knollsoft.Rectangle.plist"
    remote_src: no

- name: Rectangle Pro | Save RectangleProConfig.json file
  copy:
    src: "~/Library/Application Support/Rectangle Pro/RectangleProConfig.json"
    dest: "{{ project_path }}/files/Home/Library/Application Support/Rectangle Pro/RectangleProConfig.json"
    remote_src: yes

# - name: Rectangle Pro | Save com.knollsoft.Rectangle.plist file
#   copy:
#     src: "~/Library/SyncedPreferences/com.apple.kvs/ChangeTokens/NoEncryption/Rectangle Pro/XSYZ3E4B7D.com.knollsoft.Hookshot"
#     dest: "{{ project_path }}/files/Home/Library/SyncedPreferences/com.apple.kvs/ChangeTokens/NoEncryption/Rectangle Pro/XSYZ3E4B7D.com.knollsoft.Hookshot"
#     remote_src: no