- name: "Visual Studio Code | Check if settings.json exists"
  stat:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/settings.json"
  register: vscode_settings_stat

- name: "Visual Studio Code | Save user settings"
  copy:
    src: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/settings.json"
    dest: "{{ project_path }}/files/Home/Library/Application Support/Code/User/settings.json"
  when: vscode_settings_stat.stat.exists

- name: "Visual Studio Code | Check if keybindings.json exists"
  stat:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/keybindings.json"
  register: vscode_keybindings_stat

- name: "Visual Studio Code | Save keybindings"
  copy:
    src: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/keybindings.json"
    dest: "{{ project_path }}/files/Home/Library/Application Support/Code/User/keybindings.json"
  when: vscode_keybindings_stat.stat.exists

- name: "Visual Studio Code | Check if extensions.json exists"
  stat:
    path: "~/.vscode/extensions/extensions.json"
  register: vscode_extensions_json_stat

- name: "Visual Studio Code | Backup extensions.json"
  ansible.builtin.copy:
    src: "~/.vscode/extensions/extensions.json"
    dest: "{{ project_path }}/files/Home/.vscode/extensions/extensions.json"
    remote_src: yes
    mode: '0644'
  when: vscode_extensions_json_stat.stat.exists

- name: "Visual Studio Code | Gather list of extension directories"
  find:
    paths: "~/.vscode/extensions/"
    file_type: directory
  register: vscode_extensions

- name: "Visual Studio Code | Backup individual Visual Studio Code extensions"
  archive:
    path: "{{ item.path }}"
    dest: "{{ project_path }}/files/Home/.vscode/extensions/{{ item.path | basename }}.zip"
    format: zip
  loop: "{{ vscode_extensions.files }}"
  no_log: true
  when: vscode_extensions.files | length > 0
