- name: Wezterm | Check if wezterm config folder exists
  stat:
    path: "~/.config/wezterm/"

- name: Wezterm | Save *.lua files
  copy:
    src: "~/.config/wezterm/{{ item }}"
    dest: "{{ project_path }}/files/Home/.config/wezterm/{{ item }}"
    remote_src: no
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0755"
  loop:
    - wezterm.lua
