- name: Wezterm | Check if wezterm config folder exists
  stat:
    path: "~/.config/wezterm/"

- name: Wezterm | Backup entire config directory
  synchronize:
    src: "~/.config/wezterm/"
    dest: "{{ project_path }}/files/Home/.config/wezterm/"
    recursive: yes

- name: Wezterm | Set correct owner for wezterm config files
  ansible.builtin.file:
    path: "{{ project_path }}/files/Home/.config/wezterm/"
    owner: "{{ ansible_facts['user_id'] }}"
    state: directory
    recurse: yes
