- name: Zsh | Check if $ZSH folder exists
  stat:
    path: "{{ lookup('env', 'ZSH') | default('~/.oh-my-zsh', true) }}"
  register: oh_my_zsh_folder_check

- name: Zsh | Save .zsh* configuration files
  copy:
    src: "~/{{ item }}"
    dest: "{{ project_path }}/files/Home/{{ item }}"
    remote_src: no
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0755"
  loop:
    - .zshrc
    - .zshenv
  when: oh_my_zsh_folder_check.stat.exists

- name: Zsh | Save ~/.zprofile
  copy:
    src: "~/.zprofile"
    dest: "{{ project_path }}/files/Home/zprofile"
    remote_src: no
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0755"

  when: oh_my_zsh_folder_check.stat.exists
# - name: Zsh | Check if ~/.zshrc exists
#   stat:
#     path: ~/.zshrc
#   register: zshrc_c

# - name: Zsh | Save a copy of the existing .zshrc configuration
#   ansible.builtin.copy:
#     src: ~/.zshrc
#     dest: ~/.zshrc-backup-{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}
#     directory_mode: yes
#     remote_src: no
#   when: zshrc.stat.exists

# - name: Zsh | Oh-My-Zsh | Copy plugins to custom plugins directory
#   ansible.builtin.copy:
#     src: "/tmp/oh-my-zsh/plugins/{{ item }}/"
#     dest: "{{ lookup('env', 'ZSH_CUSTOM') or lookup('env', 'HOME') + '/.oh-my-zsh/custom' }}/plugins/{{ item }}"
#     directory_mode: yes
#     remote_src: no
#   loop:
#     - terraform
#     - ansible
#     - docker
#   when:
#     - oh_my_zsh_dir.stat.exists

# - name: Zsh | Oh-My-Zsh | Save a copy of the existing oh-my-zsh configuration
#   ansible.builtin.copy:
#     src: ~/.oh-my-zsh/
#     dest: ~/.oh-my-zsh-backup-{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}
#     directory_mode: yes
#     remote_src: no
#   when:
#     - oh_my_zsh_folder_check.stat.exists
#     - not oh_my_zsh_folder_check.stat.islnk

