  - name: Brew | Gather currently installed formulas
    command: "brew list --formula"
    register: installed_brew_formulas
    changed_when: false

  - name: Brew | Set fact for installed formulas
    set_fact:
      installed_brews: "{{ installed_brew_formulas.stdout_lines }}"

  - name: Brew | Install terminal applications
    homebrew:
      name: "{{ item }}"
      state: present
    loop: "{{ lookup('file', project_path + '/files/brew-formulas.txt').splitlines() }}"
    when: item not in installed_brews
    become: false
    ignore_errors: true

  - name: Brew | Gather currently installed GUI applications via cask
    command: "brew list --cask"
    register: installed_brew_casks
    changed_when: false

  - name: Brew | Set fact for installed cask GUI applications
    set_fact:
      installed_casks: "{{ installed_brew_casks.stdout_lines }}"

  - name: Brew | Install GUI applications
    homebrew_cask:
      name: "{{ item }}"
      state: present
    loop: "{{ lookup('file', project_path + '/files/brew-casks.txt').splitlines() }}"
    when: item not in installed_casks
    become: false
    ignore_errors: true