- name: "Contexts | Ensure the Preferences directory exists"
  file:
    path: "~/Library/Preferences"
    state: directory
    mode: '0755'

- name: "Contexts | Restore com.contextsformac.Contexts.plist file"
  copy:
    src: "{{ project_path }}/files/Home/Library/Preferences/com.contextsformac.Contexts.plist"
    dest: "~/Library/Preferences/com.contextsformac.Contexts.plist"
    remote_src: no

- name: "Contexts | Restore ContextStoreAgent.plist file"
  copy:
    src: "{{ project_path }}/files/Home/Library/Preferences/ContextStoreAgent.plist"
    dest: "~/Library/Preferences/ContextStoreAgent.plist"
    remote_src: no
