- name: Contexts | Restore plist file
  copy:
    src: "{{ project_path }}/files/Home/Library/Preferences/com.contextsformac.Contexts.plist"
    dest: "~/Library/Preferences/com.contextsformac.Contexts.plist"
    remote_src: no
