- name: fish | save fish shell config
  ansible.builtin.copy:
    src: "{{ project_path }}/files/Home/.config/fish/"
    dest: "{{ ansible_env.HOME }}/.config/fish/"
    remote_src: true
    directory_mode: true
