- name: Go | goenv | Set a variable for Go version
  set_fact:
    go_version: "1.22.2"

- name: Go | goenv | Install goenv using Homebrew
  community.general.homebrew:
    name: goenv
    state: present

- name: Go | goenv | Check if Go version is installed
  shell: "goenv versions --bare | grep '^{{ go_version }}'"
  register: go_version_installed
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Go | goenv | Install Go version
  shell: goenv install {{ go_version }}
  when: go_version_installed.stdout == ""

- name: Go | goenv | Check if Go version is set
  shell: goenv version | grep '{{ go_version }}' || true
  register: current_go_version
  changed_when: false
  ignore_errors: true

- name: Go | goenv | Set Go version as global
  shell: goenv global {{ go_version }}
  when: current_go_version.stdout.strip() != go_version
