  - name: LunarVim | Copy .zshenv
    copy:
      src: "{{ project_path }}/files/Home/.zshenv"
      dest: "{{ lookup('env','HOME') }}/.zshenv"
      force: no

  - name: LunarVim | Ensure software dependencies are installed
    homebrew:
      name:
        - nvim
        - git
        - make
        - python@3.11
        - npm
        - node
        - rust
      state: present
    when: not (lookup('file', lookup('env', 'HOME') + '/.local/bin/lvim', errors='ignore') is search(''))

  # Resolve EACCES permissions when installing packages globally
  - name: LunarVim | Ensure ~/.npm-global directory exists
    file:
      path: "{{ lookup('env','HOME') }}/.npm-global"
      state: directory

  - name: LunarVim | Configure npm global directory
    command:
      cmd: npm config set prefix '~/.npm-global'
      creates: "{{ lookup('env','HOME') }}/.npm-global"

  - name: Lunarvim | Check if '.zshrc' file exists
    stat:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
    register: zshrc_file_status

  - name: LunarVim | Ensure '.zshrc' file exists
    file:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
      state: touch
      mode: '0644'
    when: not zshrc_file_status.stat.exists

  - name: LunarVim | Ensure ~/.bashrc exists
    file:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
      state: touch
      mode: '0644'

  - name: LunarVim | Zsh | Ensure ~/.zshrc exists
    file:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
      state: touch
      mode: '0644'

  - name: LunarVim | Update PATH for npm-global
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.zshrc"
      line: 'export PATH=~/.npm-global/bin:$PATH'
      insertafter: EOF
      state: present

  - name: LunarVim | Add paths to ~/.bashrc
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
      line: 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"'
      state: present

  - name: LunarVim | Installation
    shell:
      cmd: "/bin/bash -c 'bash <(wget -O - https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)' -y"
      creates: "{{ lookup('env', 'HOME') }}/.local/bin/lvim"
    environment:
      LV_BRANCH: 'release-1.3/neovim-0.9'
    ignore_errors: true # this is here because this task will fail on MacOS VM
    
  - name: LunarVim | Set LunarVim configuration
    copy:
      src: "{{ project_path }}/files/Home/.config/lvim/config.lua"
      dest: "{{ lookup('env','HOME') }}/.config/lvim/config.lua"
      force: no

  - name: LunarVim | Push all files to ~/.config/lvim/ recursively
    synchronize:
      src: "{{ project_path }}/files/Home/.config/lvim/"
      dest: "~/.config/lvim/"
      recursive: yes
      mode: push