- name: "Rectangle Pro | Ensure Preferences directory exists"
  file:
    path: "~/Library/Preferences"
    state: directory
    mode: '0755'

- name: "Rectangle Pro | Set com.knollsoft.Rectangle.plist file"
  copy:
    src: "{{ project_path }}/files/Home/Library/Preferences/com.knollsoft.Rectangle.plist"
    dest: "~/Library/Preferences/com.knollsoft.Rectangle.plist"
    remote_src: no

- name: "Rectangle Pro | Ensure Application Support/Rectangle Pro directory exists"
  file:
    path: "~/Library/Application Support/Rectangle Pro"
    state: directory
    mode: '0755'

- name: "Rectangle Pro | Set RectangleProConfig.json file"
  copy:
    src: "{{ project_path }}/files/Home/Library/Application Support/Rectangle Pro/RectangleProConfig.json"
    dest: "~/Library/Application Support/Rectangle Pro/RectangleProConfig.json"
    remote_src: no
