- name: skhd | install skhd
  community.general.homebrew:
    name: skhd
    state: present

- name: skhd | check skhd service status
  ansible.builtin.command: pgrep -f skhd
  register: skhd_status
  failed_when: skhd_status.rc not in [0, 1]
  changed_when: False

- name: skhd | start skhd service
  ansible.builtin.command: skhd --start-service
  when: skhd_status.rc == 1

- name: skhd | set ~/.skhdrc
  copy:
    src: "{{ project_path }}/files/Home/.skhdrc"
    dest: "~/.skhdrc"
    remote_src: no
