- name: Terraform | tfenv | Install tfenv using Homebrew
  community.general.homebrew:
    name: tfenv
    state: present

- name: Terraform | tfenv | Set fact for Terraform version {{ terraform_version }}
  set_fact:
    terraform_version_installed: "{{ terraform_version }}" # Use a different variable name

- name: Terraform | tfenv | Initialize tfenv
  shell: tfenv init

- name: Terraform | tfenv | Check if Terraform version {{ terraform_version }} is installed
  shell: tfenv list | grep '{{ terraform_version }}' || true
  register: terraform_version_installed_check
  changed_when: false
  ignore_errors: true

- name: Terraform | tfenv | Install Terraform version {{ terraform_version }}
  shell: tfenv install {{ terraform_version }}
  when: terraform_version not in terraform_version_installed_check.stdout

- name: Terraform | tfenv | Check if Terraform version {{ terraform_version }} is set
  shell: tfenv version-name | grep '{{ terraform_version }}' || true
  register: current_terraform_version
  changed_when: false
  ignore_errors: true

- name: Terraform | tfenv | Set Terraform version {{ terraform_version }}
  shell: tfenv use {{ terraform_version }}
  when: current_terraform_version.stdout.strip() != terraform_version

- name: Terraform | tools | Install tfenv using Homebrew
  community.general.homebrew:
    name: tfenv
    state: present

- name: Terraform | tools | Install tflint using Homebrew
  community.general.homebrew:
    name: tflint
    state: present

- name: Terraform | tools | Install tfsec using Homebrew
  community.general.homebrew:
    name: tfsec
    state: present

- name: Terraform | tools | Install tfupdate using Homebrew
  community.general.homebrew:
    name: tfupdate
    state: present

- name: Terraform | tools | Install terraform-docs using Homebrew
  community.general.homebrew:
    name: terraform-docs
    state: present
