- name: Tmux | Install Tmux
  community.general.homebrew:
    name: tmux
    state: present

- name: "Tmux | Install tpm (tmux plugin manager)"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    clone: yes
    update: yes
  become: no
