- name: "tmux | Ensure the tmux directory exists"
  file:
    path: "~/.config/tmux"
    state: directory
    mode: "0755"

- name: "tmux | Push all files to ~/.config/tmux/ recursively"
  synchronize:
    src: "{{ project_path }}/files/Home/.config/tmux/"
    dest: "~/.config/tmux/"
    recursive: yes
    mode: push
