- name: Tmux | Ensure dotfiles repository exists
  ansible.builtin.git:
    repo: https://github.com/lowranceworks/dotfiles.git
    dest: ~/Projects/lowranceworks/dotfiles
    update: yes
    version: main

- name: Tmux | Create symlink for tmux config
  file:
    src: ~/Projects/lowranceworks/dotfiles/.config/tmux
    dest: ~/.config/tmux
    state: link

- name: Tmux | Install tpm (tmux plugin manager)
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    clone: yes
    update: yes
  become: no
