  - name: Vim | Set ~/.vimrc
    copy:
      src: "{{ project_path }}/files/Home/.vimrc"
      dest: "~/.vimrc"
      owner: "{{ lookup('env', 'USER') }}"
      mode: '0644'

  - name: Vim | Theme | Create themes/start directory
    file:
      path: "~/.vim/pack/themes/start"
      state: directory

  - name: Vim | Theme | Install Dracula theme
    git:
      repo: "https://github.com/dracula/vim.git"
      dest: "~/.vim/pack/themes/start/dracula"

  - name: Vim | Set keymappings
    synchronize:
      src: "{{ project_path }}/files/Home/.vim/keymappings.vim/"
      dest: "~/.vim/keymappings.vim"
      recursive: yes
      mode: push
