  - name: Vim | Create themes/start directory
    file:
      path: "~/.vim/pack/themes/start"
      state: directory

  - name: Vim | Install Dracula theme
    git:
      repo: "https://github.com/dracula/vim.git"
      dest: "~/.vim/pack/themes/start/dracula"

  - name: Vim | Push ~/.vimrc
    copy:
      src: "{{ project_path }}/files/Home/.vimrc"
      dest: "~/.vimrc"
      owner: "{{ lookup('env', 'USER') }}"
      mode: '0644'