- name: "Wezterm | Ensure the wezterm directory exists"
  file:
    path: "~/.config/wezterm"
    state: directory
    mode: "0755"

- name: Wezterm | Set *.lua files
  copy:
    src: "{{ project_path }}/files/Home/.config/wezterm/{{ item }}"
    dest: "~/.config/wezterm/{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0755"
  loop:
    - wezterm.lua
