- name: wezterm | Check if wezterm directory exists
  ansible.builtin.stat:
    path: "~/.config/wezterm"
  register: wezterm_dir_stat

- name: wezterm | Create ~/.config.bak directory if it doesn't exist
  ansible.builtin.file:
    path: "~/.config.bak"
    state: directory
  when: wezterm_dir_stat.stat.exists and not wezterm_dir_stat.stat.islnk

- name: wezterm | Copy files from ~/.config/wezterm to ~/.config.bak/wezterm
  ansible.builtin.copy:
    src: ~/.config/wezterm/
    dest: ~/.config.bak/wezterm/
    remote_src: true
  when: wezterm_dir_stat.stat.exists and not wezterm_dir_stat.stat.islnk

- name: wezterm | Remove old files in ~/.config/wezterm
  ansible.builtin.file:
    path: ~/.config/wezterm
    state: absent
  when: wezterm_dir_stat.stat.exists and not wezterm_dir_stat.stat.islnk
#
- name: wezterm | Move wezterm directory to ~/.config.bak if not a symlink
  ansible.builtin.file:
    src: "~/.config/wezterm/"
    dest: "~/.config.bak/wezterm"
  when: wezterm_dir_stat.stat.exists and not wezterm_dir_stat.stat.islnk

- name: wezterm | Ensure dotfiles repository exists
  ansible.builtin.git:
    repo: https://github.com/lowranceworks/dotfiles.git
    dest: ~/Projects/lowranceworks/dotfiles
    update: yes
    version: main

- name: wezterm | Create symlink for wezterm config
  file:
    src: ~/Projects/lowranceworks/dotfiles/.config/wezterm
    dest: ~/.config/wezterm
    state: link
